### ISSUE TITLE
Not properly iterating

### ISSUE THREAD

**Issue by BernierCR** [classner/pymp#4] opened 2018-07-14 22:46 UTC
Hello. I can't get this to work anymore. I follow the instructions. It starts the multiple threads, but it only ever iterates through a fraction of my range. For example, if I try to go through range(0,10000) with 8 threads, only 0-1250 gets processed. You would expect each thread to be assigned a separate portion of the range. 

Thank you.

**Comment by classner** [comment] 2018-07-16 11:59
Hi! This is strange, since this behavior should be tested. ;) Can you provide a minimal failing example?

**Comment by classner** [comment] 2018-07-21 10:58
Any news on this? Otherwise I'm going to assume the issue was resolved and will close it next week.

**Comment by BernierCR** [comment] 2018-07-23 18:17
Hey thanks for the follow-up.

I haven't had a chance to look into this further at this time. I just gave
up trying to parallelize that particular algorithm. I'm sure that in
another week or two I will try to parallelize something again. I can try to
reproduce this then. Thanks for waiting.

**Comment by classner** [comment] 2019-01-14 22:58
Hi @BernierCR ,

I would love to clean up the issues for this project. Are there any news on this? I couldn't reproduce the problem so far. If there's no response, I'm going to close this issue in the next days.

Thanks!

**Closed** 2019-03-04 00:50 UTC
